# create a sequence of waypoits [x,y,theta], with respect to map
initial_pose: [-2.0, 0.0, 0.0]

waypoints:
  - [-1.0, -0.5, 0.0]
  - [0.5, -0.5, 0.0]
  - [0.5, 0.0, 1.57]
  - [0.5, 0.5, 1.57]
  - [1.0, 0.5, 0.0]
  - [-2.0, 0.0, 0.0]
    
